from proto.<%=proto%>.<%=proto%>_grpc import <%=proto.replace(/^[a-z]/, word => `_${word.toUpperCase()}`)%>ServiceBase
from proto.<%=proto%>.<%=proto%>_pb2 import HelloRequest, HelloReply
# generated by protoc


class AiService(AiServiceBase):

    async def SayHello(self, stream):
        request: HelloRequest = await stream.recv_message()
        message = f'Hello, {request.name}!'
        await stream.send_message(HelloReply(message=message))

    async def SayHi(self, stream):
        return super().SayHi(stream)
