module.exports = {
    project: 'Create a new Mikudos project in the current folder',
    protos: 'Create a protos project with a proto folder which contains all your proto files',
    app: 'Create a Mikudos service in the current folder',
    java_app: 'Create a Mikudos service with JAVA in the current folder',
    cpp_app: 'Create a Mikudos service with C++ in the current folder',
    golang_app: 'Create a Mikudos service with GoLang in the current folder',
    golang_service: 'not support yet',
    cs_app: 'Create a Mikudos service with C# in the current folder',
    node_app: 'Create a Mikudos service with NodeJs in the current folder',
    node_service: 'not support yet',
    ruby_app: 'Create a Mikudos service with Ruby in the current folder',
    ts_app: 'Create a Mikudos service with Typescript in the current folder',
    python_app: 'Create a Mikudos service with Python in the current folder',
    python_service: 'not support yet',
    python_ai: 'Create a Mikudos service with Python for AI in the current folder',
    deployment: 'Create a Mikudos deployment template in the current folder',
    eventAggregate: 'Create a Mikudos eventAggregate service in the current folder',
    message_pusher: "Create a Mikudos message_pusher service in the current folder",
    ts_service: 'Generate a new methods implementation',
    schedule: 'Create a Mikudos schedule service within your project',
    gate: 'Create a Mikudos gate server within your project',
    rbac: 'Create a Mikudos RBAC service in the current folder',
};