app: "<%=serviceName%>-service"
consumer_group: "<%=serviceName%>-service"
default_method_regex: ".*"
brokers:
  - "127.0.0.1:9092"
mysql: "mysql://root:EventMysqlServerPassword@localhost:3306/rbac"
port: 50051
