port: 50051
brokers:
  endPoints: "127.0.0.1:9092"
  version: ""
  group: ""
  topics: ""
grpcClients:
  ai: "localhost:50052"
  learn: "learn:50051"
  users: "users:50051"
mongoDB:
  url: "yue:qiushanyu666@127.0.0.1:27017/yue"
  sslUrl: ""
  sslAuth: false
mysql:
  service: "127.0.0.1"
  port: 3306
  username: "root"
  password: "EventMysqlServerPassword"
  dbName: "events"