name: <%=serviceName%>
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - pyyaml
  - kafka-python
  - protobuf
  - openblas
  - numpy
  - scipy
  - pandas
  - Cython
  - scikit-learn==0.19.1
  - pip:
      - grpcio
      - grpcio-tools
      - grpclib
      - flask-restful==0.3.6
      - flake8
