version: "3.1"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: event
      MYSQL_PASSWORD: event
      MYSQL_ROOT_PASSWORD: EventMysqlServerPassword
    volumes:
      - "/Users/mac/develop/data/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
